# Generated by Django 3.1.4 on 2021-01-06 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0001_initial'),
        ('persona', '0003_auto_20210105_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='departamento',
            field=models.ForeignKey(default='0', on_delete=django.db.models.deletion.CASCADE, to='departamento.departamento'),
        ),
    ]
