# Generated by Django 3.1.4 on 2021-01-06 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_auto_20210106_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habilidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidad', models.CharField(max_length=50, verbose_name='Habilidades')),
            ],
            options={
                'verbose_name': 'Habilidad',
                'verbose_name_plural': 'Habilidades empleados',
            },
        ),
    ]
