# Generated by Django 3.1.4 on 2021-01-08 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_empleado_hoja_vida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='hoja_vida',
        ),
        migrations.AddField(
            model_name='empleado',
            name='full_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombres completos'),
        ),
    ]
