# Generated by Django 3.1.4 on 2021-01-20 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_empleado_savatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empleado',
            old_name='savatar',
            new_name='avatar',
        ),
    ]
